[id="con-basic-settings_{context}"]
= Basic settings
[role="_abstract"]

When you create an OIDC client, you see the following fields on the *Settings* tab.

*Client ID*:: The alpha-numeric ID string that is used in OIDC requests and in the {project_name} database to identify the client.

*Name*:: The name for the client in {project_name} UI screen. To localize
the name, set up a replacement string value. For example, a string value such as $\{myapp}.  See the link:{developerguide_link}[{developerguide_name}] for more information.

*Description*:: The description of the client.  This setting can also be localized.

ifeval::[{project_product}==true]
*Enabled*:: When turned off, the client cannot request authentication.
endif::[]
*Consent Required*:: When turned on, users see a consent page that they can use to grant access to that application.  It will also display metadata so the user knows the exact information that the client can access.

[[_access-type]]
ifeval::[{project_community}==true]
*Client authentication*:: The type of OIDC client.
* _ON_
+
For server-side clients that perform browser logins and require client secrets when making an Access Token Request. This setting should be used for server-side applications.

* _OFF_
+
  For client-side clients that perform browser logins. As it is not possible to ensure that secrets can be kept safe with client-side clients, it is important to restrict access by configuring correct redirect URIs.

endif::[]
ifeval::[{project_product}==true]
*Access Type*:: The type of OIDC client.
_Confidential_::
  For server-side clients that perform browser logins and require client secrets when making an Access Token Request. This setting should be used for server-side applications.

_Public_::
  For client-side clients that perform browser logins. As it is not possible to ensure that secrets can be kept safe with client-side clients, it is important to restrict access by configuring correct redirect URIs.

_Bearer-only_::
  The application allows only bearer token requests. When turned on, this application cannot participate in browser logins.


*Standard Flow Enabled*:: When enabled, clients can use the OIDC xref:_oidc-auth-flows-authorization[Authorization Code Flow].

*Implicit Flow Enabled*:: When enabled, clients can use the OIDC xref:_oidc-auth-flows-implicit[Implicit Flow].

*Direct Access Grants Enabled*:: When enabled, clients can use the OIDC xref:_oidc-auth-flows-direct[Direct Access Grants].

*OAuth 2.0 Device Authorization Grant Enabled*:: If this is on, clients are allowed to use the OIDC xref:con-oidc-auth-flows_server_administration_guide[Device Authorization Grant].

*OpenID Connect Client Initiated Backchannel Authentication Grant Enabled*:: 
If this is on, clients are allowed to use the OIDC xref:con-oidc-auth-flows_{context}[Client Initiated Backchannel Authentication Grant].

*Root URL*:: If {project_name} uses any configured relative URLs, this value is prepended to them.

*Valid Redirect URIs*:: Required field.  Enter a URL pattern and click *+* to add and *-* to remove existing URLs and click *Save*. You can use wildcards at the end of the URL pattern. For example $$http://host.com/*$$
+
Exclusive redirect URL patterns are typically more secure.  See xref:unspecific-redirect-uris_{context}[Unspecific Redirect URIs] for more information.

*Base URL*:: This URL is used when {project_name} needs to link to the client.

[[_admin-url]]
*Admin URL*:: Callback endpoint for a client.  The server uses this URL to make callbacks like pushing revocation policies, performing backchannel logout, and other administrative operations.  For {project_name} servlet adapters, this URL can be the root URL of the servlet application.
For more information, see link:{adapterguide_link}[{adapterguide_name}].

*Web Origins*:: Enter a URL pattern and click *+* to add and *-* to remove existing URLs. Click *Save*.
+
This option handles link:https://fetch.spec.whatwg.org/[Cross-Origin Resource Sharing (CORS)].
If browser JavaScript attempts an AJAX HTTP request to a server whose domain is different from the one that the
JavaScript code came from, the request must use CORS. The server must handle CORS requests, otherwise the browser will not display or allow the request to be processed. This protocol protects against XSS, CSRF, and other JavaScript-based attacks.
+
Domain URLs listed here are embedded within the access token sent to the client application. The client application uses this information to decide whether to allow a CORS request to be invoked on it.  Only {project_name} client adapters support this feature. See link:{adapterguide_link}[{adapterguide_name}] for more information.
endif::[]
ifeval::[{project_community}==true]

== Authentication flow

Standard Flow:: When enabled, clients can use the OIDC xref:_oidc-auth-flows-authorization[Authorization Code Flow].

Direct Access Grants:: When enabled, clients can use the OIDC xref:_oidc-auth-flows-direct[Direct Access Grants].

Implicit Flow:: When enabled, clients can use the OIDC xref:_oidc-auth-flows-implicit[Implicit Flow].

Service account roles:: When enabled, allows this client to authenticate to {project_name} and retrieve access token dedicated to this client. In terms of OAuth2 specification, this enables support of 'Client Credentials Grant' for this client.

Auth 2.0 Device Authorization Grant:: If enabled, clients are allowed to use the OIDC xref:con-oidc-auth-flows_server_administration_guide[Device Authorization Grant].

OIDC CIBA Grant:: If enabled, clients are allowed to use the OIDC xref:con-oidc-auth-flows_{context}[Client Initiated Backchannel Authentication Grant].

== Capability Config

Root URL:: If {project_name} uses any configured relative URLs, this value is prepended to them.

Home URL:: Provides the default URL for when the auth server needs to redirect or link back to the client.

Valid Redirect URIs:: Required field. Enter a URL pattern and click + to add and - to remove existing URLs and click Save. You can use wildcards at the end of the URL pattern. For example $$http://host.com/*$$
+
Exclusive redirect URL patterns are typically more secure. See xref:unspecific-redirect-uris_{context}[Unspecific Redirect URIs] for more information.

Web Origins:: Enter a URL pattern and click + to add and - to remove existing URLs. Click Save.
+
This option handles link:https://fetch.spec.whatwg.org/[Cross-Origin Resource Sharing (CORS)].
If browser JavaScript attempts an AJAX HTTP request to a server whose domain is different from the one that the
JavaScript code came from, the request must use CORS. The server must handle CORS requests, otherwise the browser will not display or allow the request to be processed. This protocol protects against XSS, CSRF, and other JavaScript-based attacks.
+
Domain URLs listed here are embedded within the access token sent to the client application. The client application uses this information to decide whether to allow a CORS request to be invoked on it. Only {project_name} client adapters support this feature. See link:{adapterguide_link}[{adapterguide_name}] for more information.

[[_admin-url]]
Admin URL:: Callback endpoint for a client. The server uses this URL to make callbacks like pushing revocation policies, performing backchannel logout, and other administrative operations. For {project_name} servlet adapters, this URL can be the root URL of the servlet application.
For more information, see link:{adapterguide_link}[{adapterguide_name}].

== Login settings

Login theme:: A theme to use for login, OTP, grant registration and forgotten password pages.

Consent required:: If enabled, users have to consent to client access.
+
For client-side clients that perform browser logins. As it is not possible to ensure that secrets can be kept safe with client-side clients, it is important to restrict access by configuring correct redirect URIs.

Display client on screen:: This switch applies if Consent Required is Off.

Off
The consent screen will contain only the consents corresponding to configured client scopes.

On
There will be also one item on the consent screen about this client itself.

Client consent screen text:: Applies if Consent required and Display client on screen are enabled. Contains the text that will be on the consent screen about permissions specific to this client.

== Logout settings

endif::[]
[[_front-channel-logout]]
*Front Channel Logout*:: If *Front Channel Logout* is enabled, the application should be able to log out users through the front channel as per link:https://openid.net/specs/openid-connect-frontchannel-1_0.html[OpenID Connect Front-Channel Logout] specification. If enabled, you should also provide the `Front-Channel Logout URL`.

*Front-Channel Logout URL*:: URL that will be used by {project_name} to send logout requests to clients through the front-channel.

[[_back-channel-logout-url]]
*Backchannel Logout URL*:: URL that will cause the client to log itself out when a logout request is sent to this realm (via end_session_endpoint). If omitted, no logout requests are sent to the client.
ifeval::[{project_community}==true]
Backchannel logout revoke offline sessions:: Specifies whether a revoke_offline_access event is included in the Logout Token when the Backchannel Logout URL is used. {project_name} will revoke offline sessions when receiving a Logout Token with this event.

endif::[]
ifeval::[{project_community}==true]
On the *Advanced* tab you'll find the following url settings
endif::[]

*Logo URL*

URL that references a logo for the Client application.

*Policy URL*

URL that the Relying Party Client provides to the End-User to read about how the profile data will be used.

*Terms of Service URL*

URL that the Relying Party Client provides to the End-User to read about the Relying Party's terms of service.
