
=== Before You Start

Before you can secure a Java Servlet application, you need to complete the installation of {project_name} and create the initial admin user as shown in  <<_install-boot, Installing and Booting>>. There is one caveat: you have to run a separate {appserver_name} instance on the same machine as the {project_name} server. This separate instance will run your Java Servlet application. For this reason, you must run the {project_name} using a different port, so that there are no port conflicts when running on the same machine.

To adjust the port used, change the value of the `jboss.socket.binding.port-offset` system property when starting the server from the command line. The value of this property is a number that will be added to the base value of every port opened by the {project_name} server.

To boot the {project_name} server while also adjusting the port:

.Linux/Unix
[source]
----
$ .../bin/standalone.sh -Djboss.socket.binding.port-offset=100
----

.Windows
[source]
----
> ...\bin\standalone.bat -Djboss.socket.binding.port-offset=100
----

After you boot {project_name}, you can access the admin console at http://localhost:8180/auth/admin/


