language: java

sudo: true

jdk:
  - oraclejdk8

env:
  - PROFILE=community
  - PROFILE=product

install: 
  - echo "travis_fold:start:install folding starts"
  - mvn clean install -DskipTests -B -q -D$PROFILE
  - echo "travis_fold:end:install folding ends"

script:
  - mvn test -f tests/pom.xml -D$PROFILE -B
