=== What Is Red Hat SSO?
Red Hat Single Sign-On (SSO) is an integrated sign-on solution available as a Red Hat JBoss Middleware for OpenShift containerized image. This image provides an authentication server for users to centrally log in, log out, register, and manage user accounts for web applications, mobile applications, and RESTful web services.

[[sso-templates]]
Red Hat offers multiple RH SSO application templates.

For RH SSO 7.1:

* *_sso71-https_*: SSO backed by a H2 database on the same pod
* *_sso71-mysql_*: SSO backed by a MySQL database on a separate pod
* *_sso71-mysql-persistent_*: SSO backed by a persistent MySQL database on a separate pod
* *_sso71-postgresql_*: SSO backed by a PostgreSQL database on a separate pod
* *_sso71-postgresql-persistent_*: SSO backed by a persistent PostgreSQL database on a separate pod

For RH SSO 7.0:

* *_sso70-https_*: SSO backed by a H2 database on the same pod
* *_sso70-mysql_*: SSO backed by a MySQL database on a separate pod
* *_sso70-mysql-persistent_*: SSO backed by a persistent MySQL database on a separate pod
* *_sso70-postgresql_*: SSO backed by a PostgreSQL database on a separate pod
* *_sso70-postgresql-persistent_*: SSO backed by a persistent PostgreSQL database on a separate pod

[NOTE]
====
The application templates for SSO 7.0 only supports replicated caching. Using distributed caching results in errors when the deployment is scaled or updated. See the link:https://access.redhat.com/documentation/en/red-hat-single-sign-on/7.0/server-installation-and-configuration-guide/#server_cache_configuration[Server Cache Configuration] chapter in the Red Hat Single Sign-On Server Installation and Configuration Guide for more information on the caching types.
====

Other templates that integrate with RH SSO are also available:

* *_eap64-sso-s2i_*: SSO-enabled Red Hat JBoss Red Hat JBoss Enterprise Application Platform(EAP) 6.4
* *_eap70-sso-s2i_*: SSO-enabled JBoss EAP 7.0
* *_datavirt63-secure-s2i_*: SSO-enabled JBoss Data Virtualization (JDV) 6.3

[NOTE]
====
These SSO-enabled templates are only supported for RH-SSO 7.0.
====

These templates contain environment variables specific to SSO that enable automatic SSO client registration when deployed. +
See xref:Auto-Man-Client-Reg[Automatic and Manual SSO Client Registration Methods] for more information.

////
[IMPORTANT]
There are significant differences in supported configurations and functionality
in the Decision Server xPaaS image compared to the regular release of JBoss BRMS.

=== How Does Red Hat SSO Work on Openshift?
////
