= RESTEasy Version Update

Updated the RESTEasy version of Keycloak Admin REST Client to the next major version.

= H2 Version Update

{project_name} ships for development purposes with an H2 database driver.
As it is intended for development purposes only, it should never be used in a production environment.

In this release, the H2 driver has been upgraded from version 1.x to version 2.x.
This change might require changes to the H2 JDBC URL or migration of the H2 database files in an existing Keycloak setup.

== Changes to the H2 JDBC URL

For Keycloak to run with its JPA legacy store with H2 version 2.x, the JDBC URL requires the attribute `NON_KEYWORDS=VALUE`.

In a setup where H2 is initialized by Keycloak without extra parameters, Keycloak will append the attribute automatically.
This is the default for development setups.

If an H2 JDBC URL is provided on the command line or in a configuration file, and it already contains the `NON_KEYWORDS=` attribute in the JDBC URL, this attribute needs to be amended with the `VALUE` keyword.

If the connection factory for the H2 database is initialized outside Keycloak, that initialization needs to take care of adding the `NON_KEYWORDS` attribute.

See the H2 documentation http://www.h2database.com/html/commands.html#set_non_keywords[on the `NON_KEYWORDS` attribute] for details.

== Upgrade of H2 database files

H2 database base files created with H2 version 1.x should not be used with version 2.x.

Purge existing H2 database files to start with an empty database, export and import the realms using Keycloak's export and import functionality, or refer to the http://www.h2database.com/html/migration-to-v2.html[migration notes on the H2 database project's website] for details on how to migrate H2 database contents.

== Upgrade of new Keycloak Operator

The following breaking changes were introduced:

* link:https://github.com/keycloak/keycloak/issues/14410[#14410] - Rename free-form field for server configuration in Keycloak CR;
* link:https://github.com/keycloak/keycloak/issues/14407[#14407] - Refine Ingress settings in Keycloak CR;
* link:https://github.com/keycloak/keycloak/issues/14396[#14396] - Add HTTP options to Keycloak CR;
* link:https://github.com/keycloak/keycloak/issues/14395[#14395] - Add hostname options to Keycloak CR;

Unfortunately, there's no automated migration. You need to reinstall the new Keycloak Operator and manually upgrade your Kubernetes CRs.

Besides that, the new Keycloak Operator OLM channel has changed to `fast`. See the details at: `link:https://github.com/keycloak/keycloak/issues/14883[#14883] - Mark Operator as stable in the OLM bundle`.
