= Keycloak uses Micrometer for metrics

Keycloak provides an optional a metrics endpoint which exports metrics in the Prometheus format.
In this release the implementation to provide this data switched from SmallRye to Micrometer, which is the https://quarkus.io/guides/micrometer[recommended metrics library for Quarkus].

Due to this change, metrics have been renamed.
The following table shows some examples.

Before upgrading it is recommended to review all metrics returned from the endpoint before and after the change, and update their usage in dashboards and alerts.

.Examples of changed metrics names
|===
|Old metric name |New metric name

|`base_gc_total`
|`jvm_gc_pause_seconds_count`

|`base_gc_time_total_seconds`
|`jvm_gc_pause_seconds_sum`

|`base_thread_count`
|`jvm_threads_live_threads`

|`vendor_agroal_*`
|`agroal_*`

|===

= Deprecated RSA_SHA1 and DSA_SHA1 algorithms for SAML

Algorithms `RSA_SHA1` and `DSA_SHA1`, which can be configured as `Signature algorithms` on SAML adapters, clients and identity providers are deprecated. We recommend to use safer
alternatives based on `SHA256` or `SHA512`. Also, verifying signatures on signed SAML documents or assertions with these
algorithms do not work on Java 17 or higher. If you use this algorithm and the other party consuming your SAML documents is running on Java 17 or higher, verifying signatures will not work.

The possible workaround is to remove algorithms such as `++http://www.w3.org/2000/09/xmldsig#rsa-sha1++` or `++http://www.w3.org/2000/09/xmldsig#dsa-sha1++` from the list
of "disallowed algorithms" configured on property `jdk.xml.dsig.secureValidationPolicy` in the file `$JAVA_HOME/conf/security/java.security`.

= Browsers need to support SameSite=None

The cookies from the login flow are now served with `SameSite=None` as default.

Old browsers might not be compatible with this, see https://www.chromium.org/updates/same-site/incompatible-clients/[known incompatible clients] and https://caniuse.com/?search=SameSite%3DNone[Can I use SameSite=None] for details.
At this point, we believe the only thing affected is the OIDC session status iframe.

There are two possible mitigations:

* The OIDC session status iframe can be disabled in the client side configuration, see https://www.keycloak.org/docs/latest/securing_apps/index.html#session-status-iframe[Session Status iframe] in the {adapterguide_name}.

* Serving cookies without `SameSite=None` is now a deprecated feature named `legacy-cookies`, which is disabled by default, and will be removed in a future version.
To ease the migration path, it can be enabled to allow more time to upgrade any outdated browsers.
To enable it, see the https://www.keycloak.org/server/features[Enabling and disabling features] guide.
