
=== Master Realm Access Control

The `master` realm in {project_name} is a special realm. Users in the {project_name} `master` realm can manage multiple realms on the {project_name} server. {project_name} automatically creates roles that grant specific permissions to access the new realm, upon realm creation. Access to the Admin Console and Admin REST endpoints is controlled by mapping the roles to users in the `master` realm. Mapping roles to users in the `master` realm controls access to the Admin Console and Admin REST endpoints.

{project_name} can create multiple super users and users that can manage specific realms only.

==== Global Roles

Two realm-level roles exist in the `master` realm.

* admin
* create-realm        

Users with the `admin` role are super users and have access to manage any realm on the server. Users with the `create-realm` role can create new realms and these users have full access to any new realm they create.

==== Realm Specific Roles

You can grant management privileges, for multiple realms in the system, to admin users within the `master` realm.
Each realm in {project_name} is represented by a client in the `master` realm. The format of the name of the client is `<realm name>-realm`. These clients have client-level roles which define various level of access for managing an individual realm.

The roles available are: 

* view-realm
* view-users
* view-clients
* view-events
* manage-realm
* manage-users
* create-client
* manage-clients
* manage-events            
* view-identity-providers
* manage-identity-providers
* impersonation

Users with these roles can use that specific part of the Admin Console only.

[NOTE]
====
Administrators with the `manage-users` role can assign admin roles to users that only administrators with the `manage-users` role have. For example, if an administrator has the `manage-users` role but does not have the `manage-realm` role, they will be unable to assign the `manage-realm` role to other users.
====
