// Metadata created by nebel
//
// UserStory: As an RH SSO customer, I want to deploy specific to complete the initial configuration

[id="deploy-code"]
= Installing sample application code

ifeval::[{project_community}==true]
To make this application functional as a secure application, you will need to install the sample code provided. You obtain the code by cloning the {quickstartRepo_name} repository at {quickstartRepo_link}. The quickstarts are designed to work with the most recent Keycloak release.

endif::[]

ifeval::[{project_product}==true]
To make this application functional as a secure application, you install some sample code. You obtain the code by cloning the repository at {quickstartRepo_link}. The quickstarts are designed to work with the most recent {project_name} release.

endif::[]

.Prerequisites

You must have the following installed on your machine and available in your PATH.

* Java JDK 8
* Apache Maven 3.1.1 or higher
* Git

.Procedure

. Make sure your {appserver_name} application server is started.
. Download, build, and install the code using the following commands.

ifeval::[{project_product}==true]
+
NOTE: In the following git command, use the branch that matches your version of {project_name}. 
endif::[]

+
.Clone Project
[source, subs="attributes"]
----
$ git clone {quickstartRepo_link}
$ cd {quickstartRepo_dir}/app-profile-jee-vanilla
$ mvn clean wildfly:deploy
----

+
During installation, you will see some text scroll by in the application server console window.

. Confirm that the application is successfully installed. Go to http://localhost:8080/vanilla where a login page should appear.

+
If you click *Login*, the browser will pop up a BASIC auth login dialog. However, the application is not yet secured by any identity provider, so anything you enter in the dialog box will result in a `Forbidden` message being sent back by the server.

. Confirm that the application is currently secured by `BASIC` authentication by finding the setting in the application's `web.xml` file. 
