[[_getting_started_overview]]
== Getting Started

Before you can use this tutorial, you need to complete the installation of {book_project_name} and create the initial admin user as shown in the link:{book_gettingstarted_link}[{book_gettingstarted_name}] tutorial.
There is one caveat to this. You have to run a separate {book_appServer} instance on the same machine as {book_project_name} Server. This separate instance will run your Java Servlet application. Because of this you will have to run the {book_project_name} under a different port so that there are no port conflicts when running on the same machine. Use the `jboss.socket.binding.port-offset` system property on the command line. The value of this property is a number that will be added to the base value of every port opened by {book_project_name} Server.

To boot {book_project_name} Server:

.Linux/Unix
[source]
----
$ .../bin/standalone.sh -Djboss.socket.binding.port-offset=100
----

.Windows
[source]
----
> ...\bin\standalone.bat -Djboss.socket.binding.port-offset=100
----

For more details about how to install and configure a {book_appServer}, please follow the steps on the link:{book_adapterguide_link}[{book_adapterguide_name}] tutorial.

After installing and booting both servers you should be able to access {book_project_name} Admin Console at http://localhost:8180/auth/admin/ and also the {book_appServer} instance at
http://localhost:8080.
