= Allow setting a base URL when configuring the hostname

In this release, we are introducing two additional server options to set a base URL for front end and Admin Console URLs.

* `hostname-url`
* `hostname-admin-url`

More details can be found at the https://www.keycloak.org/server/hostname[Configuring the Hostname Guide].

= Improvements to `kc.bat` when running Keycloak on Windows

In this release, we are making important changes to `kc.bat` to give the same experience as when running on Linux.

= Upgrade of embedded H2 database

{project_name} ships for development purposes with an H2 database driver. As it is intended for development purposes only, it should never be used in a production environment.

In this release, the H2 driver has been upgraded from version 1.x to version 2.x.
See link:{upgradingguide_link}[{upgradingguide_name}] for details on how to migrate.

= New Keycloak Operator is Production ready now

After being available as a Preview distribution in the last [N] releases, the new Keycloak Operator has faced some improvements and fixes, therefore it is ready for Production.
However, the following breaking changes were introduced:

* link:https://github.com/keycloak/keycloak/issues/14410[#14410] - Rename free-form field for server configuration in Keycloak CR;
* link:https://github.com/keycloak/keycloak/issues/14407[#14407] - Refine Ingress settings in Keycloak CR;
* link:https://github.com/keycloak/keycloak/issues/14396[#14396] - Add HTTP options to Keycloak CR;
* link:https://github.com/keycloak/keycloak/issues/14395[#14395] - Add hostname options to Keycloak CR;

Please, see link:{upgradingguide_link}[{upgradingguide_name}] for details on how to migrate it.
