= Keycloak uses Micrometer for metrics

Keycloak provides an optional a metrics endpoint which exports metrics in the Prometheus format.
In this release the implementation to provide this data switched from SmallRye to Micrometer.
Due to this change, metrics have been renamed.

See the migration guide for details.

= Hashicop Vault no longer supported

We removed the out-of-box support for Hashicorp vault in this release.

See this https://github.com/keycloak/keycloak/discussions/16446[discussion] for more details.

= Metrics for embedded Infinispan as preview

When metrics are enabled and {project_name} uses the embedded {jdgserver_name}, the metrics endpoint exposes information about caches using the `/metrics` endpoint in the metrics with names starting with `vendor_cache_*`.
Those metrics use the original pattern as provided by {jdgserver_name}.
They are currently a preview feature and might change in upcoming releases, especially when the {jdgserver_name} is updated in such a release.
