= Highlights

== WildFly 17 Upgrade

Keycloak server was upgraded to use WildFly 17 under the covers.

== Tomcat 9 adapter support

Java adapter for Apache Tomcat 8 and Apache Tomcat 9 was unified and now it serves for both of them.

== Gatekeeper

It is now possible to force cookie encryption for hybrid scenarios where the token in the header may be in the clear and the token in cookie is always encrypted. 

There was a bug on Gatekeeper when enabled the `Revoke Refresh Token` on the Keycloak server. The issue was fixed.

Thanks to https://github.com/fredbi[fredbi] for contributing a signficant part of this work.

== New Account Console

A lot of work has been done on the new Account Console and Account REST API. It's not quite ready yet, but it's getting
there and hopefully will be fully done for Keycloak 8.

== Testing and release automation

The Keycloak team has spent a significant amount of time on automation around testing and releases both for Keycloak and
Red Hat Single Sign-On.

= Other improvements

* PKCE support added to JavaScript adapter. Thanks to https://github.com/thomasdarimont[thomasdarimont]
* Oracle database support added to Keycloak container image. Thanks to https://github.com/nerdstep[nerdstep]
* Clock Skew support added to SAML adapter. Thanks to https://github.com/steevebtib[steevebtib]
* TypeScript support for Node.js adapter. Thanks to https://github.com/evanshortiss[evanshortiss]
* Allow Gatekeeper to provide unencrypted token in header, while encrypting in cookie. Thanks to https://github.com/fredbi[fredbi]
